// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package anonymous.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_Multiply extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long Num1;
	private java.lang.Long Num2;

	public JA_Multiply(IContext context, java.lang.Long Num1, java.lang.Long Num2)
	{
		super(context);
		this.Num1 = Num1;
		this.Num2 = Num2;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return multiply(Num1, Num2);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Multiply";
	}

	// BEGIN EXTRA CODE
	public java.lang.Long multiply(java.lang.Long _num1, java.lang.Long _num2)
	{
		return _num1*_num2;
	}
	
	// END EXTRA CODE
}
