// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package salesmanager.actions;

import java.math.BigDecimal;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_CommitWarehouse extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __NewWarehouse;
	private salesmanager.proxies.Warehouse NewWarehouse;

	public JA_CommitWarehouse(IContext context, IMendixObject NewWarehouse)
	{
		super(context);
		this.__NewWarehouse = NewWarehouse;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.NewWarehouse = __NewWarehouse == null ? null : salesmanager.proxies.Warehouse.initialize(getContext(), __NewWarehouse);

		// BEGIN USER CODE
		NewWarehouse.setName("Java");
		BigDecimal latitude = new BigDecimal(99);
		NewWarehouse.setLatitude(latitude);
		
		BigDecimal longitude = new BigDecimal(99);
		NewWarehouse.setLongitude(longitude);
		
		Core.commit(getContext(), NewWarehouse.getMendixObject());
		return null;
				
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CommitWarehouse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
