// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package salesmanager.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_GenerateSalesId extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long SalesId;

	public JA_GenerateSalesId(IContext context, java.lang.Long SalesId)
	{
		super(context);
		this.SalesId = SalesId;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.lang.String generatedSaleId = generateSalesId(SalesId,getContext());
		
		return generatedSaleId;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GenerateSalesId";
	}

	// BEGIN EXTRA CODE
	private java.lang.String generateSalesId(java.lang.Long salesId, IContext context) throws CoreException {
		java.util.Map<java.lang.String,Object> params = new java.util.HashMap<>();
		params.put("SalesId", salesId);
		
		java.lang.String generatedSalesId = com.mendix.core.Core.microflowCall("SalesManager.ACT_GenerateSalesId").
				inTransaction(true).
				withParams(params).execute(this.getContext());
		
		return generatedSalesId;
	}
	
	// END EXTRA CODE
}
