// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package salesmanager.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_SetShare extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Share;
	private salesmanager.proxies.Share Share;

	public JA_SetShare(IContext context, IMendixObject Share)
	{
		super(context);
		this.__Share = Share;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Share = __Share == null ? null : salesmanager.proxies.Share.initialize(getContext(), __Share);

		// BEGIN USER CODE
		Share.setName("Enter name please...");
		Share.setMail("Enter mail please...");		
		return this.__Share;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SetShare";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
