// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anychart_buildingblocks.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AnyChart_BuildingBlocks module

	public static java.lang.String getVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AnyChart_BuildingBlocks.Version");
	}
}