// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anonymous.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Anonymous module
	public static void aCT_RegisterUser(IContext context, anonymous.proxies.Anonymous _anonymous)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Anonymous", _anonymous == null ? null : _anonymous.getMendixObject());
		Core.microflowCall("Anonymous.ACT_RegisterUser").withParams(params).execute(context);
	}
	public static anonymous.proxies.Anonymous dS_Anonymous(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Anonymous.DS_Anonymous").withParams(params).execute(context);
		return result == null ? null : anonymous.proxies.Anonymous.initialize(context, result);
	}
}