// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} mail
 * @param {string} name
 * @returns {Promise.<string>}
 */
export async function JS_SendMailWithMicroflow(mail, name) {
	// BEGIN USER CODE
	console.warn(mail,name);
	return new Promise((resolve, reject) => {
		mx.data.create({
			entity: "SalesManager.Share",
			callback: function (shareObjectInsideRunTime) {
				shareObjectInsideRunTime.set("Mail", mail);
				shareObjectInsideRunTime.set("Name", name);

				mx.data.action({
					params: {
						applyto: "selection",
						actionname: "SalesManager.ACT_SendSharingMail",
						guids: [shareObjectInsideRunTime.getGuid()]
					},				
					callback: function (responseMessage) {
						// expect single MxObject
						console.warn(responseMessage)
						resolve(responseMessage);
					},
					error: function (error) {
						//alert(error.message);
						reject(new Error("Some error occured."))
					}
				});
			},
			error: function (e) {
				reject(new Error("Some error occured."))
			}
		});

	})
	// END USER CODE
}
