define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js":
/*!**********************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js ***!
  \**********************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "HideProgress": () => (/* binding */ HideProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Hides default progress bar
 * @param {Big} identifier - Identifier of ui which should be hidden. This param is required
 * @returns {Promise.<void>}
 */

async function HideProgress(identifier) {
  // BEGIN USER CODE
  if (identifier == null) {
    return Promise.reject(new Error("Input parameter 'Identifier' is required"));
  }

  mx.ui.hideProgress(Number(identifier));
  return Promise.resolve(); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js":
/*!**********************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js ***!
  \**********************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "ShowProgress": () => (/* binding */ ShowProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows default progress bar
 * @param {string} message - The text to show while loading.
 * @param {boolean} blocking - Block the user interface immediately.
 * @returns {Promise.<Big>}
 */

async function ShowProgress(message, blocking) {
  // BEGIN USER CODE
  const id = mx.ui.showProgress(message, blocking);

  if (id !== undefined) {
    return Promise.resolve(new big_js__WEBPACK_IMPORTED_MODULE_0__.Big(id));
  }

  return Promise.reject(new Error("Could not open the loading dialog")); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js":
/*!*************************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js ***!
  \*************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_GetUserComments": () => (/* binding */ JS_GetUserComments)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE

function createUserComment(comment) {
  return new Promise((resolve, reject) => {
    mx.data.create({
      entity: "SalesManager.Comment",
      callback: function (mxObject) {
        mxObject.getAttributes().forEach(function (attributeName) {
          const attributeValue = comment[attributeName];

          if (attributeValue) {
            mxObject.set(attributeName, attributeValue);
          }
        });
        resolve(mxObject);
      },
      error: function (e) {
        reject(new Error("couldnt create a comment entity"));
      }
    });
  });
} // END EXTRA CODE

/**
 * @returns {Promise.<MxObject[]>}
 */


async function JS_GetUserComments() {
  // BEGIN USER CODE
  const endpoint = "https://jsonplaceholder.typicode.com/comments";
  const res = await fetch(endpoint);
  const json = await res.json();
  const userComments = json.map(createUserComment);
  return Promise.all(userComments); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js":
/*!***********************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js ***!
  \***********************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_OpenSharePage": () => (/* binding */ JS_OpenSharePage)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */

async function JS_OpenSharePage() {
  // BEGIN USER CODE
  return new Promise((resolve, reject) => {
    mx.ui.openForm("SalesManager/Share_Web.page.xml", {
      location: "popup",
      callback: function (form) {
        let close = document.getElementsByClassName("close")[0];
        close.remove();
        let share = document.getElementsByClassName("share")[0];
        share.remove();
      }
    });
  }); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js":
/*!*******************************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js ***!
  \*******************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_SendMailWithMicroflow": () => (/* binding */ JS_SendMailWithMicroflow)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} mail
 * @param {string} name
 * @returns {Promise.<string>}
 */

async function JS_SendMailWithMicroflow(mail, name) {
  // BEGIN USER CODE
  console.warn(mail, name);
  return new Promise((resolve, reject) => {
    mx.data.create({
      entity: "SalesManager.Share",
      callback: function (shareObjectInsideRunTime) {
        shareObjectInsideRunTime.set("Mail", mail);
        shareObjectInsideRunTime.set("Name", name);
        mx.data.action({
          params: {
            applyto: "selection",
            actionname: "SalesManager.ACT_SendSharingMail",
            guids: [shareObjectInsideRunTime.getGuid()]
          },
          callback: function (responseMessage) {
            // expect single MxObject
            console.warn(responseMessage);
            resolve(responseMessage);
          },
          error: function (error) {
            //alert(error.message);
            reject(new Error("Some error occured."));
          }
        });
      },
      error: function (e) {
        reject(new Error("Some error occured."));
      }
    });
  }); // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!*****************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/deployment/tmp/jsactions.js ***!
  \*****************************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "SalesManager$JS_OpenSharePage": () => (/* binding */ SalesManager$JS_OpenSharePage),
/* harmony export */   "SalesManager$JS_GetUserComments": () => (/* binding */ SalesManager$JS_GetUserComments),
/* harmony export */   "NanoflowCommons$ShowProgress": () => (/* binding */ NanoflowCommons$ShowProgress),
/* harmony export */   "NanoflowCommons$HideProgress": () => (/* binding */ NanoflowCommons$HideProgress),
/* harmony export */   "SalesManager$JS_SendMailWithMicroflow": () => (/* binding */ SalesManager$JS_SendMailWithMicroflow)
/* harmony export */ });
const SalesManager$JS_OpenSharePage = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_OpenSharePage.js"))).JS_OpenSharePage;
const SalesManager$JS_GetUserComments = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_GetUserComments.js"))).JS_GetUserComments;
const NanoflowCommons$ShowProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js"))).ShowProgress;
const NanoflowCommons$HideProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js"))).HideProgress;
const SalesManager$JS_SendMailWithMicroflow = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_SendMailWithMicroflow.js"))).JS_SendMailWithMicroflow;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQyxZQUFmLENBQTRCQyxVQUE1QixFQUF3QztBQUM5QztBQUNHLE1BQUlBLFVBQVUsSUFBSSxJQUFsQixFQUF3QjtBQUNwQixXQUFPQyxPQUFPLENBQUNDLE1BQVIsQ0FBZSxJQUFJQyxLQUFKLENBQVUsMENBQVYsQ0FBZixDQUFQO0FBQ0g7O0FBQ0RDLEVBQUFBLEVBQUUsQ0FBQ0MsRUFBSCxDQUFNQyxZQUFOLENBQW1CQyxNQUFNLENBQUNQLFVBQUQsQ0FBekI7QUFDQSxTQUFPQyxPQUFPLENBQUNPLE9BQVIsRUFBUCxDQU4yQyxDQU85QztBQUNBOzs7Ozs7Ozs7Ozs7Ozs7O0FDekJEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUMsWUFBZixDQUE0QkMsT0FBNUIsRUFBcUNDLFFBQXJDLEVBQStDO0FBQ3JEO0FBQ0csUUFBTUMsRUFBRSxHQUFHUixFQUFFLENBQUNDLEVBQUgsQ0FBTVEsWUFBTixDQUFtQkgsT0FBbkIsRUFBNEJDLFFBQTVCLENBQVg7O0FBQ0EsTUFBSUMsRUFBRSxLQUFLRSxTQUFYLEVBQXNCO0FBQ2xCLFdBQU9iLE9BQU8sQ0FBQ08sT0FBUixDQUFnQixJQUFJVix1Q0FBSixDQUFRYyxFQUFSLENBQWhCLENBQVA7QUFDSDs7QUFDRCxTQUFPWCxPQUFPLENBQUNDLE1BQVIsQ0FBZSxJQUFJQyxLQUFKLENBQVUsbUNBQVYsQ0FBZixDQUFQLENBTmtELENBT3JEO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7QUMxQkQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTs7QUFDQSxTQUFTWSxpQkFBVCxDQUEyQkMsT0FBM0IsRUFBb0M7QUFDbkMsU0FBTyxJQUFJZixPQUFKLENBQVksQ0FBQ08sT0FBRCxFQUFVTixNQUFWLEtBQXFCO0FBQ3ZDRSxJQUFBQSxFQUFFLENBQUNhLElBQUgsQ0FBUUMsTUFBUixDQUFlO0FBQ2RDLE1BQUFBLE1BQU0sRUFBRSxzQkFETTtBQUVkQyxNQUFBQSxRQUFRLEVBQUUsVUFBVUMsUUFBVixFQUFvQjtBQUM3QkEsUUFBQUEsUUFBUSxDQUFDQyxhQUFULEdBQXlCQyxPQUF6QixDQUFpQyxVQUFVQyxhQUFWLEVBQXlCO0FBQ3pELGdCQUFNQyxjQUFjLEdBQUdULE9BQU8sQ0FBQ1EsYUFBRCxDQUE5Qjs7QUFDQSxjQUFJQyxjQUFKLEVBQW9CO0FBQ25CSixZQUFBQSxRQUFRLENBQUNLLEdBQVQsQ0FBYUYsYUFBYixFQUE0QkMsY0FBNUI7QUFDQTtBQUNELFNBTEQ7QUFNQWpCLFFBQUFBLE9BQU8sQ0FBQ2EsUUFBRCxDQUFQO0FBQ0EsT0FWYTtBQVdkTSxNQUFBQSxLQUFLLEVBQUUsVUFBVUMsQ0FBVixFQUFhO0FBQ25CMUIsUUFBQUEsTUFBTSxDQUFDLElBQUlDLEtBQUosQ0FBVSxpQ0FBVixDQUFELENBQU47QUFDQTtBQWJhLEtBQWY7QUFlQSxHQWhCTSxDQUFQO0FBaUJBLEVBR0Q7O0FBRUE7QUFDQTtBQUNBOzs7QUFDTyxlQUFlMEIsa0JBQWYsR0FBb0M7QUFDMUM7QUFDQSxRQUFNQyxRQUFRLEdBQUcsK0NBQWpCO0FBQ0EsUUFBTUMsR0FBRyxHQUFHLE1BQU1DLEtBQUssQ0FBQ0YsUUFBRCxDQUF2QjtBQUNBLFFBQU1HLElBQUksR0FBRyxNQUFNRixHQUFHLENBQUNFLElBQUosRUFBbkI7QUFDQSxRQUFNQyxZQUFZLEdBQUdELElBQUksQ0FBQ0UsR0FBTCxDQUFTcEIsaUJBQVQsQ0FBckI7QUFFQSxTQUFPZCxPQUFPLENBQUNtQyxHQUFSLENBQVlGLFlBQVosQ0FBUCxDQVAwQyxDQVUxQztBQUNBOzs7Ozs7Ozs7Ozs7Ozs7O0FDL0NEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUcsZ0JBQWYsR0FBa0M7QUFDeEM7QUFDQSxTQUFPLElBQUlwQyxPQUFKLENBQVksQ0FBQ08sT0FBRCxFQUFVTixNQUFWLEtBQXFCO0FBQ3RDRSxJQUFBQSxFQUFFLENBQUNDLEVBQUgsQ0FBTWlDLFFBQU4sQ0FBZSxpQ0FBZixFQUFrRDtBQUNqREMsTUFBQUEsUUFBUSxFQUFFLE9BRHVDO0FBRWpEbkIsTUFBQUEsUUFBUSxFQUFFLFVBQVVvQixJQUFWLEVBQWdCO0FBQ3pCLFlBQUlDLEtBQUssR0FBR0MsUUFBUSxDQUFDQyxzQkFBVCxDQUFnQyxPQUFoQyxFQUF5QyxDQUF6QyxDQUFaO0FBQ0FGLFFBQUFBLEtBQUssQ0FBQ0csTUFBTjtBQUNBLFlBQUlDLEtBQUssR0FBR0gsUUFBUSxDQUFDQyxzQkFBVCxDQUFnQyxPQUFoQyxFQUF5QyxDQUF6QyxDQUFaO0FBQ0FFLFFBQUFBLEtBQUssQ0FBQ0QsTUFBTjtBQUNBO0FBUGdELEtBQWxEO0FBU0QsR0FWTSxDQUFQLENBRndDLENBYXhDO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7QUM3QkQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUUsd0JBQWYsQ0FBd0NDLElBQXhDLEVBQThDQyxJQUE5QyxFQUFvRDtBQUMxRDtBQUNBQyxFQUFBQSxPQUFPLENBQUNDLElBQVIsQ0FBYUgsSUFBYixFQUFrQkMsSUFBbEI7QUFDQSxTQUFPLElBQUkvQyxPQUFKLENBQVksQ0FBQ08sT0FBRCxFQUFVTixNQUFWLEtBQXFCO0FBQ3ZDRSxJQUFBQSxFQUFFLENBQUNhLElBQUgsQ0FBUUMsTUFBUixDQUFlO0FBQ2RDLE1BQUFBLE1BQU0sRUFBRSxvQkFETTtBQUVkQyxNQUFBQSxRQUFRLEVBQUUsVUFBVStCLHdCQUFWLEVBQW9DO0FBQzdDQSxRQUFBQSx3QkFBd0IsQ0FBQ3pCLEdBQXpCLENBQTZCLE1BQTdCLEVBQXFDcUIsSUFBckM7QUFDQUksUUFBQUEsd0JBQXdCLENBQUN6QixHQUF6QixDQUE2QixNQUE3QixFQUFxQ3NCLElBQXJDO0FBRUE1QyxRQUFBQSxFQUFFLENBQUNhLElBQUgsQ0FBUW1DLE1BQVIsQ0FBZTtBQUNkQyxVQUFBQSxNQUFNLEVBQUU7QUFDUEMsWUFBQUEsT0FBTyxFQUFFLFdBREY7QUFFUEMsWUFBQUEsVUFBVSxFQUFFLGtDQUZMO0FBR1BDLFlBQUFBLEtBQUssRUFBRSxDQUFDTCx3QkFBd0IsQ0FBQ00sT0FBekIsRUFBRDtBQUhBLFdBRE07QUFNZHJDLFVBQUFBLFFBQVEsRUFBRSxVQUFVc0MsZUFBVixFQUEyQjtBQUNwQztBQUNBVCxZQUFBQSxPQUFPLENBQUNDLElBQVIsQ0FBYVEsZUFBYjtBQUNBbEQsWUFBQUEsT0FBTyxDQUFDa0QsZUFBRCxDQUFQO0FBQ0EsV0FWYTtBQVdkL0IsVUFBQUEsS0FBSyxFQUFFLFVBQVVBLEtBQVYsRUFBaUI7QUFDdkI7QUFDQXpCLFlBQUFBLE1BQU0sQ0FBQyxJQUFJQyxLQUFKLENBQVUscUJBQVYsQ0FBRCxDQUFOO0FBQ0E7QUFkYSxTQUFmO0FBZ0JBLE9BdEJhO0FBdUJkd0IsTUFBQUEsS0FBSyxFQUFFLFVBQVVDLENBQVYsRUFBYTtBQUNuQjFCLFFBQUFBLE1BQU0sQ0FBQyxJQUFJQyxLQUFKLENBQVUscUJBQVYsQ0FBRCxDQUFOO0FBQ0E7QUF6QmEsS0FBZjtBQTRCQSxHQTdCTSxDQUFQLENBSDBELENBaUMxRDtBQUNBOzs7Ozs7Ozs7O0FDbkREOzs7Ozs7VUNBQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBOztVQUVBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBOzs7OztXQ3RCQTtXQUNBO1dBQ0E7V0FDQTtXQUNBO1dBQ0EsaUNBQWlDLFdBQVc7V0FDNUM7V0FDQTs7Ozs7V0NQQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLHlDQUF5Qyx3Q0FBd0M7V0FDakY7V0FDQTtXQUNBOzs7OztXQ1BBOzs7OztXQ0FBO1dBQ0E7V0FDQTtXQUNBLHVEQUF1RCxpQkFBaUI7V0FDeEU7V0FDQSxnREFBZ0QsYUFBYTtXQUM3RDs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDTk8sTUFBTXdELDZCQUE2QixHQUFHLFlBQVksQ0FBQyxNQUFNLG1WQUFQLEVBQTRIdEIsZ0JBQTlLO0FBQ0EsTUFBTXVCLCtCQUErQixHQUFHLFlBQVksQ0FBQyxNQUFNLHVWQUFQLEVBQThIL0Isa0JBQWxMO0FBQ0EsTUFBTWdDLDRCQUE0QixHQUFHLFlBQVksQ0FBQyxNQUFNLGlWQUFQLEVBQTJIcEQsWUFBNUs7QUFDQSxNQUFNcUQsNEJBQTRCLEdBQUcsWUFBWSxDQUFDLE1BQU0saVZBQVAsRUFBMkgvRCxZQUE1SztBQUNBLE1BQU1nRSxxQ0FBcUMsR0FBRyxZQUFZLENBQUMsTUFBTSxtV0FBUCxFQUFvSWpCLHdCQUE5TCxDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvSGlkZVByb2dyZXNzLmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1Nob3dQcm9ncmVzcy5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvdGFyaWsvRG9jdW1lbnRzL01lbmRpeC9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9zYWxlc21hbmFnZXIvYWN0aW9ucy9KU19HZXRVc2VyQ29tbWVudHMuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2Uvc2FsZXNtYW5hZ2VyL2FjdGlvbnMvSlNfT3BlblNoYXJlUGFnZS5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvdGFyaWsvRG9jdW1lbnRzL01lbmRpeC9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9zYWxlc21hbmFnZXIvYWN0aW9ucy9KU19TZW5kTWFpbFdpdGhNaWNyb2Zsb3cuanMiLCJ3ZWJwYWNrOi8vL2V4dGVybmFsIGFtZCBcImJpZy5qc1wiIiwid2VicGFjazovLy93ZWJwYWNrL2Jvb3RzdHJhcCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2NvbXBhdCBnZXQgZGVmYXVsdCBleHBvcnQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9kZWZpbmUgcHJvcGVydHkgZ2V0dGVycyIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2hhc093blByb3BlcnR5IHNob3J0aGFuZCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL21ha2UgbmFtZXNwYWNlIG9iamVjdCIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvdGFyaWsvRG9jdW1lbnRzL01lbmRpeC9lY29tbWVyY2UtYXBwLW1haW4vZGVwbG95bWVudC90bXAvanNhY3Rpb25zLmpzIl0sInNvdXJjZXNDb250ZW50IjpbIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBIaWRlcyBkZWZhdWx0IHByb2dyZXNzIGJhclxyXG4gKiBAcGFyYW0ge0JpZ30gaWRlbnRpZmllciAtIElkZW50aWZpZXIgb2YgdWkgd2hpY2ggc2hvdWxkIGJlIGhpZGRlbi4gVGhpcyBwYXJhbSBpcyByZXF1aXJlZFxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSGlkZVByb2dyZXNzKGlkZW50aWZpZXIpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGlmIChpZGVudGlmaWVyID09IG51bGwpIHtcclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiSW5wdXQgcGFyYW1ldGVyICdJZGVudGlmaWVyJyBpcyByZXF1aXJlZFwiKSk7XHJcbiAgICB9XHJcbiAgICBteC51aS5oaWRlUHJvZ3Jlc3MoTnVtYmVyKGlkZW50aWZpZXIpKTtcclxuICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUoKTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIFNob3dzIGRlZmF1bHQgcHJvZ3Jlc3MgYmFyXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSBtZXNzYWdlIC0gVGhlIHRleHQgdG8gc2hvdyB3aGlsZSBsb2FkaW5nLlxyXG4gKiBAcGFyYW0ge2Jvb2xlYW59IGJsb2NraW5nIC0gQmxvY2sgdGhlIHVzZXIgaW50ZXJmYWNlIGltbWVkaWF0ZWx5LlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48QmlnPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBTaG93UHJvZ3Jlc3MobWVzc2FnZSwgYmxvY2tpbmcpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGNvbnN0IGlkID0gbXgudWkuc2hvd1Byb2dyZXNzKG1lc3NhZ2UsIGJsb2NraW5nKTtcclxuICAgIGlmIChpZCAhPT0gdW5kZWZpbmVkKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXcgQmlnKGlkKSk7XHJcbiAgICB9XHJcbiAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiQ291bGQgbm90IG9wZW4gdGhlIGxvYWRpbmcgZGlhbG9nXCIpKTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG5mdW5jdGlvbiBjcmVhdGVVc2VyQ29tbWVudChjb21tZW50KSB7XHJcblx0cmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcclxuXHRcdG14LmRhdGEuY3JlYXRlKHtcclxuXHRcdFx0ZW50aXR5OiBcIlNhbGVzTWFuYWdlci5Db21tZW50XCIsXHJcblx0XHRcdGNhbGxiYWNrOiBmdW5jdGlvbiAobXhPYmplY3QpIHtcclxuXHRcdFx0XHRteE9iamVjdC5nZXRBdHRyaWJ1dGVzKCkuZm9yRWFjaChmdW5jdGlvbiAoYXR0cmlidXRlTmFtZSkge1xyXG5cdFx0XHRcdFx0Y29uc3QgYXR0cmlidXRlVmFsdWUgPSBjb21tZW50W2F0dHJpYnV0ZU5hbWVdO1xyXG5cdFx0XHRcdFx0aWYgKGF0dHJpYnV0ZVZhbHVlKSB7XHJcblx0XHRcdFx0XHRcdG14T2JqZWN0LnNldChhdHRyaWJ1dGVOYW1lLCBhdHRyaWJ1dGVWYWx1ZSlcclxuXHRcdFx0XHRcdH1cclxuXHRcdFx0XHR9KVxyXG5cdFx0XHRcdHJlc29sdmUobXhPYmplY3QpXHJcblx0XHRcdH0sXHJcblx0XHRcdGVycm9yOiBmdW5jdGlvbiAoZSkge1xyXG5cdFx0XHRcdHJlamVjdChuZXcgRXJyb3IoXCJjb3VsZG50IGNyZWF0ZSBhIGNvbW1lbnQgZW50aXR5XCIpKVxyXG5cdFx0XHR9XHJcblx0XHR9KTtcclxuXHR9KVxyXG59XHJcblxyXG5cclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48TXhPYmplY3RbXT59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfR2V0VXNlckNvbW1lbnRzKCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdGNvbnN0IGVuZHBvaW50ID0gXCJodHRwczovL2pzb25wbGFjZWhvbGRlci50eXBpY29kZS5jb20vY29tbWVudHNcIjtcclxuXHRjb25zdCByZXMgPSBhd2FpdCBmZXRjaChlbmRwb2ludCk7XHJcblx0Y29uc3QganNvbiA9IGF3YWl0IHJlcy5qc29uKCk7XHJcblx0Y29uc3QgdXNlckNvbW1lbnRzID0ganNvbi5tYXAoY3JlYXRlVXNlckNvbW1lbnQpO1xyXG5cclxuXHRyZXR1cm4gUHJvbWlzZS5hbGwodXNlckNvbW1lbnRzKTtcclxuXHJcblxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEpTX09wZW5TaGFyZVBhZ2UoKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcblx0cmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcclxuXHRcdFx0bXgudWkub3BlbkZvcm0oXCJTYWxlc01hbmFnZXIvU2hhcmVfV2ViLnBhZ2UueG1sXCIsIHtcclxuXHRcdFx0XHRsb2NhdGlvbjogXCJwb3B1cFwiLFxyXG5cdFx0XHRcdGNhbGxiYWNrOiBmdW5jdGlvbiAoZm9ybSkge1xyXG5cdFx0XHRcdFx0bGV0IGNsb3NlID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcImNsb3NlXCIpWzBdO1xyXG5cdFx0XHRcdFx0Y2xvc2UucmVtb3ZlKCk7XHJcblx0XHRcdFx0XHRsZXQgc2hhcmUgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5Q2xhc3NOYW1lKFwic2hhcmVcIilbMF07XHJcblx0XHRcdFx0XHRzaGFyZS5yZW1vdmUoKTtcdFx0XHJcblx0XHRcdFx0fVxyXG5cdFx0XHR9KTtcdFxyXG5cdH0pXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcGFyYW0ge3N0cmluZ30gbWFpbFxyXG4gKiBAcGFyYW0ge3N0cmluZ30gbmFtZVxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48c3RyaW5nPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19TZW5kTWFpbFdpdGhNaWNyb2Zsb3cobWFpbCwgbmFtZSkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdGNvbnNvbGUud2FybihtYWlsLG5hbWUpO1xyXG5cdHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XHJcblx0XHRteC5kYXRhLmNyZWF0ZSh7XHJcblx0XHRcdGVudGl0eTogXCJTYWxlc01hbmFnZXIuU2hhcmVcIixcclxuXHRcdFx0Y2FsbGJhY2s6IGZ1bmN0aW9uIChzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUpIHtcclxuXHRcdFx0XHRzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuc2V0KFwiTWFpbFwiLCBtYWlsKTtcclxuXHRcdFx0XHRzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuc2V0KFwiTmFtZVwiLCBuYW1lKTtcclxuXHJcblx0XHRcdFx0bXguZGF0YS5hY3Rpb24oe1xyXG5cdFx0XHRcdFx0cGFyYW1zOiB7XHJcblx0XHRcdFx0XHRcdGFwcGx5dG86IFwic2VsZWN0aW9uXCIsXHJcblx0XHRcdFx0XHRcdGFjdGlvbm5hbWU6IFwiU2FsZXNNYW5hZ2VyLkFDVF9TZW5kU2hhcmluZ01haWxcIixcclxuXHRcdFx0XHRcdFx0Z3VpZHM6IFtzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUuZ2V0R3VpZCgpXVxyXG5cdFx0XHRcdFx0fSxcdFx0XHRcdFxyXG5cdFx0XHRcdFx0Y2FsbGJhY2s6IGZ1bmN0aW9uIChyZXNwb25zZU1lc3NhZ2UpIHtcclxuXHRcdFx0XHRcdFx0Ly8gZXhwZWN0IHNpbmdsZSBNeE9iamVjdFxyXG5cdFx0XHRcdFx0XHRjb25zb2xlLndhcm4ocmVzcG9uc2VNZXNzYWdlKVxyXG5cdFx0XHRcdFx0XHRyZXNvbHZlKHJlc3BvbnNlTWVzc2FnZSk7XHJcblx0XHRcdFx0XHR9LFxyXG5cdFx0XHRcdFx0ZXJyb3I6IGZ1bmN0aW9uIChlcnJvcikge1xyXG5cdFx0XHRcdFx0XHQvL2FsZXJ0KGVycm9yLm1lc3NhZ2UpO1xyXG5cdFx0XHRcdFx0XHRyZWplY3QobmV3IEVycm9yKFwiU29tZSBlcnJvciBvY2N1cmVkLlwiKSlcclxuXHRcdFx0XHRcdH1cclxuXHRcdFx0XHR9KTtcclxuXHRcdFx0fSxcclxuXHRcdFx0ZXJyb3I6IGZ1bmN0aW9uIChlKSB7XHJcblx0XHRcdFx0cmVqZWN0KG5ldyBFcnJvcihcIlNvbWUgZXJyb3Igb2NjdXJlZC5cIikpXHJcblx0XHRcdH1cclxuXHRcdH0pO1xyXG5cclxuXHR9KVxyXG5cdC8vIEVORCBVU0VSIENPREVcclxufVxyXG4iLCJtb2R1bGUuZXhwb3J0cyA9IF9fV0VCUEFDS19FWFRFUk5BTF9NT0RVTEVfYmlnX2pzX187IiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBTYWxlc01hbmFnZXIkSlNfT3BlblNoYXJlUGFnZSA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX09wZW5TaGFyZVBhZ2VcIikpLkpTX09wZW5TaGFyZVBhZ2U7XG5leHBvcnQgY29uc3QgU2FsZXNNYW5hZ2VyJEpTX0dldFVzZXJDb21tZW50cyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX0dldFVzZXJDb21tZW50c1wiKSkuSlNfR2V0VXNlckNvbW1lbnRzO1xuZXhwb3J0IGNvbnN0IE5hbm9mbG93Q29tbW9ucyRTaG93UHJvZ3Jlc3MgPSBhc3luYyAoKSA9PiAoYXdhaXQgaW1wb3J0KFwiQzovVXNlcnMvdGFyaWsvRG9jdW1lbnRzL01lbmRpeC9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9TaG93UHJvZ3Jlc3NcIikpLlNob3dQcm9ncmVzcztcbmV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvSGlkZVByb2dyZXNzXCIpKS5IaWRlUHJvZ3Jlc3M7XG5leHBvcnQgY29uc3QgU2FsZXNNYW5hZ2VyJEpTX1NlbmRNYWlsV2l0aE1pY3JvZmxvdyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL3NhbGVzbWFuYWdlci9hY3Rpb25zL0pTX1NlbmRNYWlsV2l0aE1pY3JvZmxvd1wiKSkuSlNfU2VuZE1haWxXaXRoTWljcm9mbG93O1xuIl0sIm5hbWVzIjpbIkJpZyIsIkhpZGVQcm9ncmVzcyIsImlkZW50aWZpZXIiLCJQcm9taXNlIiwicmVqZWN0IiwiRXJyb3IiLCJteCIsInVpIiwiaGlkZVByb2dyZXNzIiwiTnVtYmVyIiwicmVzb2x2ZSIsIlNob3dQcm9ncmVzcyIsIm1lc3NhZ2UiLCJibG9ja2luZyIsImlkIiwic2hvd1Byb2dyZXNzIiwidW5kZWZpbmVkIiwiY3JlYXRlVXNlckNvbW1lbnQiLCJjb21tZW50IiwiZGF0YSIsImNyZWF0ZSIsImVudGl0eSIsImNhbGxiYWNrIiwibXhPYmplY3QiLCJnZXRBdHRyaWJ1dGVzIiwiZm9yRWFjaCIsImF0dHJpYnV0ZU5hbWUiLCJhdHRyaWJ1dGVWYWx1ZSIsInNldCIsImVycm9yIiwiZSIsIkpTX0dldFVzZXJDb21tZW50cyIsImVuZHBvaW50IiwicmVzIiwiZmV0Y2giLCJqc29uIiwidXNlckNvbW1lbnRzIiwibWFwIiwiYWxsIiwiSlNfT3BlblNoYXJlUGFnZSIsIm9wZW5Gb3JtIiwibG9jYXRpb24iLCJmb3JtIiwiY2xvc2UiLCJkb2N1bWVudCIsImdldEVsZW1lbnRzQnlDbGFzc05hbWUiLCJyZW1vdmUiLCJzaGFyZSIsIkpTX1NlbmRNYWlsV2l0aE1pY3JvZmxvdyIsIm1haWwiLCJuYW1lIiwiY29uc29sZSIsIndhcm4iLCJzaGFyZU9iamVjdEluc2lkZVJ1blRpbWUiLCJhY3Rpb24iLCJwYXJhbXMiLCJhcHBseXRvIiwiYWN0aW9ubmFtZSIsImd1aWRzIiwiZ2V0R3VpZCIsInJlc3BvbnNlTWVzc2FnZSIsIlNhbGVzTWFuYWdlciRKU19PcGVuU2hhcmVQYWdlIiwiU2FsZXNNYW5hZ2VyJEpTX0dldFVzZXJDb21tZW50cyIsIk5hbm9mbG93Q29tbW9ucyRTaG93UHJvZ3Jlc3MiLCJOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzIiwiU2FsZXNNYW5hZ2VyJEpTX1NlbmRNYWlsV2l0aE1pY3JvZmxvdyJdLCJzb3VyY2VSb290IjoiIn0=