define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js":
/*!**********************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js ***!
  \**********************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "HideProgress": () => (/* binding */ HideProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Hides default progress bar
 * @param {Big} identifier - Identifier of ui which should be hidden. This param is required
 * @returns {Promise.<void>}
 */

async function HideProgress(identifier) {
  // BEGIN USER CODE
  if (identifier == null) {
    return Promise.reject(new Error("Input parameter 'Identifier' is required"));
  }

  mx.ui.hideProgress(Number(identifier));
  return Promise.resolve(); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js":
/*!**********************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js ***!
  \**********************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "ShowProgress": () => (/* binding */ ShowProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows default progress bar
 * @param {string} message - The text to show while loading.
 * @param {boolean} blocking - Block the user interface immediately.
 * @returns {Promise.<Big>}
 */

async function ShowProgress(message, blocking) {
  // BEGIN USER CODE
  const id = mx.ui.showProgress(message, blocking);

  if (id !== undefined) {
    return Promise.resolve(new big_js__WEBPACK_IMPORTED_MODULE_0__.Big(id));
  }

  return Promise.reject(new Error("Could not open the loading dialog")); // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_ThrowRandomError.js":
/*!**************************************************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_ThrowRandomError.js ***!
  \**************************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "JS_ThrowRandomError": () => (/* binding */ JS_ThrowRandomError)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
 // BEGIN EXTRA CODE

async function waitFiveSecond() {
  let randomNumber = Math.floor(Math.random() * 100);
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (randomNumber) {
        mx.ui.error("Something went wrong." + " " + randomNumber.toString());
        return resolve(true);
      }

      return reject(new Error("random number couldn't be generated."));
    }, 5000);
  });
} // END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */


async function JS_ThrowRandomError() {
  // BEGIN USER CODE
  const result = await waitFiveSecond();
  return result; // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/*!*****************************************************************************************************!*\
  !*** ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/deployment/tmp/jsactions.js ***!
  \*****************************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "NanoflowCommons$ShowProgress": () => (/* binding */ NanoflowCommons$ShowProgress),
/* harmony export */   "SalesManager$JS_ThrowRandomError": () => (/* binding */ SalesManager$JS_ThrowRandomError),
/* harmony export */   "NanoflowCommons$HideProgress": () => (/* binding */ NanoflowCommons$HideProgress)
/* harmony export */ });
const NanoflowCommons$ShowProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/ShowProgress.js"))).ShowProgress;
const SalesManager$JS_ThrowRandomError = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_ThrowRandomError */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/salesmanager/actions/JS_ThrowRandomError.js"))).JS_ThrowRandomError;
const NanoflowCommons$HideProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress */ "../../../../../../Users/tarik/Documents/Mendix/ecommerce-app-main/javascriptsource/nanoflowcommons/actions/HideProgress.js"))).HideProgress;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtDQUdBO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUFDTyxlQUFlQyxZQUFmLENBQTRCQyxVQUE1QixFQUF3QztBQUM5QztBQUNHLE1BQUlBLFVBQVUsSUFBSSxJQUFsQixFQUF3QjtBQUNwQixXQUFPQyxPQUFPLENBQUNDLE1BQVIsQ0FBZSxJQUFJQyxLQUFKLENBQVUsMENBQVYsQ0FBZixDQUFQO0FBQ0g7O0FBQ0RDLEVBQUFBLEVBQUUsQ0FBQ0MsRUFBSCxDQUFNQyxZQUFOLENBQW1CQyxNQUFNLENBQUNQLFVBQUQsQ0FBekI7QUFDQSxTQUFPQyxPQUFPLENBQUNPLE9BQVIsRUFBUCxDQU4yQyxDQU85QztBQUNBOzs7Ozs7Ozs7Ozs7Ozs7O0FDekJEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0NBR0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FBQ08sZUFBZUMsWUFBZixDQUE0QkMsT0FBNUIsRUFBcUNDLFFBQXJDLEVBQStDO0FBQ3JEO0FBQ0csUUFBTUMsRUFBRSxHQUFHUixFQUFFLENBQUNDLEVBQUgsQ0FBTVEsWUFBTixDQUFtQkgsT0FBbkIsRUFBNEJDLFFBQTVCLENBQVg7O0FBQ0EsTUFBSUMsRUFBRSxLQUFLRSxTQUFYLEVBQXNCO0FBQ2xCLFdBQU9iLE9BQU8sQ0FBQ08sT0FBUixDQUFnQixJQUFJVix1Q0FBSixDQUFRYyxFQUFSLENBQWhCLENBQVA7QUFDSDs7QUFDRCxTQUFPWCxPQUFPLENBQUNDLE1BQVIsQ0FBZSxJQUFJQyxLQUFKLENBQVUsbUNBQVYsQ0FBZixDQUFQLENBTmtELENBT3JEO0FBQ0E7Ozs7Ozs7Ozs7Ozs7Ozs7QUMxQkQ7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Q0FHQTs7QUFDQSxlQUFlWSxjQUFmLEdBQWdDO0FBQy9CLE1BQUlDLFlBQVksR0FBR0MsSUFBSSxDQUFDQyxLQUFMLENBQVdELElBQUksQ0FBQ0UsTUFBTCxLQUFnQixHQUEzQixDQUFuQjtBQUNBLFNBQU8sSUFBSWxCLE9BQUosQ0FBWSxDQUFDTyxPQUFELEVBQVVOLE1BQVYsS0FBcUI7QUFDdkNrQixJQUFBQSxVQUFVLENBQUMsTUFBTTtBQUNoQixVQUFJSixZQUFKLEVBQWtCO0FBQ2pCWixRQUFBQSxFQUFFLENBQUNDLEVBQUgsQ0FBTWdCLEtBQU4sQ0FBWSwwQkFBMEIsR0FBMUIsR0FBZ0NMLFlBQVksQ0FBQ00sUUFBYixFQUE1QztBQUNBLGVBQU9kLE9BQU8sQ0FBQyxJQUFELENBQWQ7QUFDQTs7QUFDRCxhQUFPTixNQUFNLENBQUMsSUFBSUMsS0FBSixDQUFVLHNDQUFWLENBQUQsQ0FBYjtBQUNBLEtBTlMsRUFNUCxJQU5PLENBQVY7QUFPQSxHQVJNLENBQVA7QUFTQSxFQUVEOztBQUVBO0FBQ0E7QUFDQTs7O0FBQ08sZUFBZW9CLG1CQUFmLEdBQXFDO0FBQzNDO0FBQ0EsUUFBTUMsTUFBTSxHQUFHLE1BQU1ULGNBQWMsRUFBbkM7QUFDQSxTQUFPUyxNQUFQLENBSDJDLENBSTNDO0FBQ0E7Ozs7Ozs7Ozs7QUNqQ0Q7Ozs7OztVQ0FBO1VBQ0E7O1VBRUE7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7O1VBRUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7Ozs7O1dDdEJBO1dBQ0E7V0FDQTtXQUNBO1dBQ0E7V0FDQSxpQ0FBaUMsV0FBVztXQUM1QztXQUNBOzs7OztXQ1BBO1dBQ0E7V0FDQTtXQUNBO1dBQ0EseUNBQXlDLHdDQUF3QztXQUNqRjtXQUNBO1dBQ0E7Ozs7O1dDUEE7Ozs7O1dDQUE7V0FDQTtXQUNBO1dBQ0EsdURBQXVELGlCQUFpQjtXQUN4RTtXQUNBLGdEQUFnRCxhQUFhO1dBQzdEOzs7Ozs7Ozs7Ozs7Ozs7O0FDTk8sTUFBTUMsNEJBQTRCLEdBQUcsWUFBWSxDQUFDLE1BQU0saVZBQVAsRUFBMkhoQixZQUE1SztBQUNBLE1BQU1pQixnQ0FBZ0MsR0FBRyxZQUFZLENBQUMsTUFBTSx5VkFBUCxFQUErSEgsbUJBQXBMO0FBQ0EsTUFBTUksNEJBQTRCLEdBQUcsWUFBWSxDQUFDLE1BQU0saVZBQVAsRUFBMkg1QixZQUE1SyxDIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvSGlkZVByb2dyZXNzLmpzIiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1Nob3dQcm9ncmVzcy5qcyIsIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvdGFyaWsvRG9jdW1lbnRzL01lbmRpeC9lY29tbWVyY2UtYXBwLW1haW4vamF2YXNjcmlwdHNvdXJjZS9zYWxlc21hbmFnZXIvYWN0aW9ucy9KU19UaHJvd1JhbmRvbUVycm9yLmpzIiwid2VicGFjazovLy9leHRlcm5hbCBhbWQgXCJiaWcuanNcIiIsIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9jb21wYXQgZ2V0IGRlZmF1bHQgZXhwb3J0Iiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvZGVmaW5lIHByb3BlcnR5IGdldHRlcnMiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9oYXNPd25Qcm9wZXJ0eSBzaG9ydGhhbmQiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svcnVudGltZS9tYWtlIG5hbWVzcGFjZSBvYmplY3QiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2RlcGxveW1lbnQvdG1wL2pzYWN0aW9ucy5qcyJdLCJzb3VyY2VzQ29udGVudCI6WyIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgeyBCaWcgfSBmcm9tIFwiYmlnLmpzXCI7XHJcblxyXG4vLyBCRUdJTiBFWFRSQSBDT0RFXHJcbi8vIEVORCBFWFRSQSBDT0RFXHJcblxyXG4vKipcclxuICogSGlkZXMgZGVmYXVsdCBwcm9ncmVzcyBiYXJcclxuICogQHBhcmFtIHtCaWd9IGlkZW50aWZpZXIgLSBJZGVudGlmaWVyIG9mIHVpIHdoaWNoIHNob3VsZCBiZSBoaWRkZW4uIFRoaXMgcGFyYW0gaXMgcmVxdWlyZWRcclxuICogQHJldHVybnMge1Byb21pc2UuPHZvaWQ+fVxyXG4gKi9cclxuZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIEhpZGVQcm9ncmVzcyhpZGVudGlmaWVyKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiAgICBpZiAoaWRlbnRpZmllciA9PSBudWxsKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIklucHV0IHBhcmFtZXRlciAnSWRlbnRpZmllcicgaXMgcmVxdWlyZWRcIikpO1xyXG4gICAgfVxyXG4gICAgbXgudWkuaGlkZVByb2dyZXNzKE51bWJlcihpZGVudGlmaWVyKSk7XHJcbiAgICByZXR1cm4gUHJvbWlzZS5yZXNvbHZlKCk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBTaG93cyBkZWZhdWx0IHByb2dyZXNzIGJhclxyXG4gKiBAcGFyYW0ge3N0cmluZ30gbWVzc2FnZSAtIFRoZSB0ZXh0IHRvIHNob3cgd2hpbGUgbG9hZGluZy5cclxuICogQHBhcmFtIHtib29sZWFufSBibG9ja2luZyAtIEJsb2NrIHRoZSB1c2VyIGludGVyZmFjZSBpbW1lZGlhdGVseS5cclxuICogQHJldHVybnMge1Byb21pc2UuPEJpZz59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gU2hvd1Byb2dyZXNzKG1lc3NhZ2UsIGJsb2NraW5nKSB7XHJcblx0Ly8gQkVHSU4gVVNFUiBDT0RFXHJcbiAgICBjb25zdCBpZCA9IG14LnVpLnNob3dQcm9ncmVzcyhtZXNzYWdlLCBibG9ja2luZyk7XHJcbiAgICBpZiAoaWQgIT09IHVuZGVmaW5lZCkge1xyXG4gICAgICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUobmV3IEJpZyhpZCkpO1xyXG4gICAgfVxyXG4gICAgcmV0dXJuIFByb21pc2UucmVqZWN0KG5ldyBFcnJvcihcIkNvdWxkIG5vdCBvcGVuIHRoZSBsb2FkaW5nIGRpYWxvZ1wiKSk7XHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuYXN5bmMgZnVuY3Rpb24gd2FpdEZpdmVTZWNvbmQoKSB7XHJcblx0bGV0IHJhbmRvbU51bWJlciA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDEwMCk7XHJcblx0cmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcclxuXHRcdHNldFRpbWVvdXQoKCkgPT4ge1xyXG5cdFx0XHRpZiAocmFuZG9tTnVtYmVyKSB7XHJcblx0XHRcdFx0bXgudWkuZXJyb3IoXCJTb21ldGhpbmcgd2VudCB3cm9uZy5cIiArIFwiIFwiICsgcmFuZG9tTnVtYmVyLnRvU3RyaW5nKCkpO1xyXG5cdFx0XHRcdHJldHVybiByZXNvbHZlKHRydWUpO1xyXG5cdFx0XHR9XHJcblx0XHRcdHJldHVybiByZWplY3QobmV3IEVycm9yKFwicmFuZG9tIG51bWJlciBjb3VsZG4ndCBiZSBnZW5lcmF0ZWQuXCIpKVxyXG5cdFx0fSwgNTAwMClcclxuXHR9KVxyXG59XHJcblxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19UaHJvd1JhbmRvbUVycm9yKCkge1xyXG5cdC8vIEJFR0lOIFVTRVIgQ09ERVxyXG5cdGNvbnN0IHJlc3VsdCA9IGF3YWl0IHdhaXRGaXZlU2Vjb25kKCk7XHJcblx0cmV0dXJuIHJlc3VsdDtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwibW9kdWxlLmV4cG9ydHMgPSBfX1dFQlBBQ0tfRVhURVJOQUxfTU9EVUxFX2JpZ19qc19fOyIsIi8vIFRoZSBtb2R1bGUgY2FjaGVcbnZhciBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX18gPSB7fTtcblxuLy8gVGhlIHJlcXVpcmUgZnVuY3Rpb25cbmZ1bmN0aW9uIF9fd2VicGFja19yZXF1aXJlX18obW9kdWxlSWQpIHtcblx0Ly8gQ2hlY2sgaWYgbW9kdWxlIGlzIGluIGNhY2hlXG5cdHZhciBjYWNoZWRNb2R1bGUgPSBfX3dlYnBhY2tfbW9kdWxlX2NhY2hlX19bbW9kdWxlSWRdO1xuXHRpZiAoY2FjaGVkTW9kdWxlICE9PSB1bmRlZmluZWQpIHtcblx0XHRyZXR1cm4gY2FjaGVkTW9kdWxlLmV4cG9ydHM7XG5cdH1cblx0Ly8gQ3JlYXRlIGEgbmV3IG1vZHVsZSAoYW5kIHB1dCBpdCBpbnRvIHRoZSBjYWNoZSlcblx0dmFyIG1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF0gPSB7XG5cdFx0Ly8gbm8gbW9kdWxlLmlkIG5lZWRlZFxuXHRcdC8vIG5vIG1vZHVsZS5sb2FkZWQgbmVlZGVkXG5cdFx0ZXhwb3J0czoge31cblx0fTtcblxuXHQvLyBFeGVjdXRlIHRoZSBtb2R1bGUgZnVuY3Rpb25cblx0X193ZWJwYWNrX21vZHVsZXNfX1ttb2R1bGVJZF0obW9kdWxlLCBtb2R1bGUuZXhwb3J0cywgX193ZWJwYWNrX3JlcXVpcmVfXyk7XG5cblx0Ly8gUmV0dXJuIHRoZSBleHBvcnRzIG9mIHRoZSBtb2R1bGVcblx0cmV0dXJuIG1vZHVsZS5leHBvcnRzO1xufVxuXG4iLCIvLyBnZXREZWZhdWx0RXhwb3J0IGZ1bmN0aW9uIGZvciBjb21wYXRpYmlsaXR5IHdpdGggbm9uLWhhcm1vbnkgbW9kdWxlc1xuX193ZWJwYWNrX3JlcXVpcmVfXy5uID0gKG1vZHVsZSkgPT4ge1xuXHR2YXIgZ2V0dGVyID0gbW9kdWxlICYmIG1vZHVsZS5fX2VzTW9kdWxlID9cblx0XHQoKSA9PiAobW9kdWxlWydkZWZhdWx0J10pIDpcblx0XHQoKSA9PiAobW9kdWxlKTtcblx0X193ZWJwYWNrX3JlcXVpcmVfXy5kKGdldHRlciwgeyBhOiBnZXR0ZXIgfSk7XG5cdHJldHVybiBnZXR0ZXI7XG59OyIsIi8vIGRlZmluZSBnZXR0ZXIgZnVuY3Rpb25zIGZvciBoYXJtb255IGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uZCA9IChleHBvcnRzLCBkZWZpbml0aW9uKSA9PiB7XG5cdGZvcih2YXIga2V5IGluIGRlZmluaXRpb24pIHtcblx0XHRpZihfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZGVmaW5pdGlvbiwga2V5KSAmJiAhX193ZWJwYWNrX3JlcXVpcmVfXy5vKGV4cG9ydHMsIGtleSkpIHtcblx0XHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBrZXksIHsgZW51bWVyYWJsZTogdHJ1ZSwgZ2V0OiBkZWZpbml0aW9uW2tleV0gfSk7XG5cdFx0fVxuXHR9XG59OyIsIl9fd2VicGFja19yZXF1aXJlX18ubyA9IChvYmosIHByb3ApID0+IChPYmplY3QucHJvdG90eXBlLmhhc093blByb3BlcnR5LmNhbGwob2JqLCBwcm9wKSkiLCIvLyBkZWZpbmUgX19lc01vZHVsZSBvbiBleHBvcnRzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLnIgPSAoZXhwb3J0cykgPT4ge1xuXHRpZih0eXBlb2YgU3ltYm9sICE9PSAndW5kZWZpbmVkJyAmJiBTeW1ib2wudG9TdHJpbmdUYWcpIHtcblx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgU3ltYm9sLnRvU3RyaW5nVGFnLCB7IHZhbHVlOiAnTW9kdWxlJyB9KTtcblx0fVxuXHRPYmplY3QuZGVmaW5lUHJvcGVydHkoZXhwb3J0cywgJ19fZXNNb2R1bGUnLCB7IHZhbHVlOiB0cnVlIH0pO1xufTsiLCJleHBvcnQgY29uc3QgTmFub2Zsb3dDb21tb25zJFNob3dQcm9ncmVzcyA9IGFzeW5jICgpID0+IChhd2FpdCBpbXBvcnQoXCJDOi9Vc2Vycy90YXJpay9Eb2N1bWVudHMvTWVuZGl4L2Vjb21tZXJjZS1hcHAtbWFpbi9qYXZhc2NyaXB0c291cmNlL25hbm9mbG93Y29tbW9ucy9hY3Rpb25zL1Nob3dQcm9ncmVzc1wiKSkuU2hvd1Byb2dyZXNzO1xuZXhwb3J0IGNvbnN0IFNhbGVzTWFuYWdlciRKU19UaHJvd1JhbmRvbUVycm9yID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2Uvc2FsZXNtYW5hZ2VyL2FjdGlvbnMvSlNfVGhyb3dSYW5kb21FcnJvclwiKSkuSlNfVGhyb3dSYW5kb21FcnJvcjtcbmV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL3RhcmlrL0RvY3VtZW50cy9NZW5kaXgvZWNvbW1lcmNlLWFwcC1tYWluL2phdmFzY3JpcHRzb3VyY2UvbmFub2Zsb3djb21tb25zL2FjdGlvbnMvSGlkZVByb2dyZXNzXCIpKS5IaWRlUHJvZ3Jlc3M7XG4iXSwibmFtZXMiOlsiQmlnIiwiSGlkZVByb2dyZXNzIiwiaWRlbnRpZmllciIsIlByb21pc2UiLCJyZWplY3QiLCJFcnJvciIsIm14IiwidWkiLCJoaWRlUHJvZ3Jlc3MiLCJOdW1iZXIiLCJyZXNvbHZlIiwiU2hvd1Byb2dyZXNzIiwibWVzc2FnZSIsImJsb2NraW5nIiwiaWQiLCJzaG93UHJvZ3Jlc3MiLCJ1bmRlZmluZWQiLCJ3YWl0Rml2ZVNlY29uZCIsInJhbmRvbU51bWJlciIsIk1hdGgiLCJmbG9vciIsInJhbmRvbSIsInNldFRpbWVvdXQiLCJlcnJvciIsInRvU3RyaW5nIiwiSlNfVGhyb3dSYW5kb21FcnJvciIsInJlc3VsdCIsIk5hbm9mbG93Q29tbW9ucyRTaG93UHJvZ3Jlc3MiLCJTYWxlc01hbmFnZXIkSlNfVGhyb3dSYW5kb21FcnJvciIsIk5hbm9mbG93Q29tbW9ucyRIaWRlUHJvZ3Jlc3MiXSwic291cmNlUm9vdCI6IiJ9